# Health

Provides API interfaces for checking health status.  This is the status of the <%= application_name %> appliance itself, which includes elasticsearch, mysql etc.

## Get Health Status

```shell
curl "<%= curl_url %>/api/health" \
  -H "Authorization: BEARER <%= curl_token %>"
```

> The above command returns JSON structured like this:

```json
{
  "health": {
    "success": true,
    "date": "2019-12-23T19:14:41Z",
    "cpu": {
      "success": true,
      "cpuLoad": 0.5126493909536541,
      "cpuTotalLoad": 5.302748759909017,
      "processorCount": 16,
      "processTime": 52169711.18,
      "systemLoad": 2.9423828125,
      "status": "ok"
    },
    "memory": {
      "success": true,
      "maxMemory": 7635730432,
      "totalMemory": 6765936640,
      "freeMemory": 197682472,
      "usedMemory": 6568254168,
      "systemMemory": 34359738368,
      "comittedMemory": 18334928896,
      "systemFreeMemory": 474562560.0,
      "systemSwap": 34359738368,
      "systemFreeSwap": 34359738368,
      "swapPercent": 0.0,
      "memoryPercent": 0.9707826894,
      "systemMemoryPercent": 0.9861884117126465,
      "status": "warning",
      "statusMessage": "heavy memory usage, consider increasing memory"
    }
}
```

> The above JSON is abbreviated, the actual response contains more data.

This endpoint retrieves health info about the <%= application_name %> appliance such as cpu, memory and database usage. Elasticsearch statistics and queue usage are also returned.

### HTTP Request

`GET <%= api_url %>/api/health`


## Get All Health Alarms

```shell
curl "<%= curl_url %>/api/health/alarms" \
  -H "Authorization: BEARER <%= curl_token %>"
```

> The above command returns JSON structured like this:

```json
{
  "alarms": [
    
  ],
  "meta": {
    "size": 2,
    "total": 2,
    "offset": 0,
    "max": 25
  }
}
```

This endpoint retrieves all health alarms, which are Operation notifications from Cloud and other Service Integrations. These alarms are not generated by <%= application_name %> but synced and displayed for visibility in <%= application_name %>.
By default only open alarms are returned. Open alarms are those that have not yet been acknowledged.

### HTTP Request

`GET <%= api_url %>/api/health/alarms`

### Query Parameters

Parameter | Default | Description
--------- | ------- | -----------
max | 25 | Max number of results to return
offset | 0 | Offset of records you want to load
sort | name | Sort order
direction | asc | Sort direction, use 'desc' to reverse sort
phrase |  | Filter by matching name
name |  | Filter by name
acknowledged |  | Filter by acknowledged flag

## Get a Specific Health Alarm

```shell
curl "<%= curl_url %>/api/health/alarms/1" \
  -H "Authorization: BEARER <%= curl_token %>"
```

> The above command returns JSON structured like this:

```json
{
  "alarm": {
    "id": 1,
    "name": "foobar",
    "dateCreated": "2019-11-17T05:59:20+0000",
    "lastUpdated": "2019-11-17T05:59:20+0000"
  }
}

```

This endpoint will retrieve a specific health alarm by ID.

### HTTP Request

`GET <%= api_url %>/api/health/alarms/:id`

### URL Parameters

Parameter | Description
--------- | -----------
ID | The ID of the alarm

## Acknowledge a Health Alarm

```shell
curl -XPUT "<%= curl_url %>/api/health/alarms/1/acknowledge" \
  -H "Authorization: BEARER <%= curl_token %>" \
  -H "Content-Type: application/json" \
  -d '{"alarm":{
    "acknowledged": true,
  }}'
```

> The above command returns JSON structured like this:

```json
{
  "success": true
}
```
This endpoint acknowledge the specified health alarm. This marks it as acknowledged so it will no longer appear in the list of open alarms.

### HTTP Request

`PUT <%= api_url %>/api/health/alarms/1/acknowledge`

### URL Parameters

Parameter | Description
--------- | -----------
ID | The ID of the alarm

### JSON Parameters

The following parameters are passed inside an object named `alarm`.

Parameter | Default | Description
--------- | ------- | -----------
acknowledged      |  | Pass `true` to ackowledge an alarm, or pass `false` to unacknowledge it.

## Acknowledge Many Health Alarms

```shell
curl -XPUT "<%= curl_url %>/api/health/alarms/acknowledge" \
  -H "Authorization: BEARER <%= curl_token %>" \
  -H "Content-Type: application/json" \
  -d '{
    "ids": [1,2,3,4,5],
    "alarm":{
      "acknowledged": true
  }}'
```

> The above command returns JSON structured like this:

```json
{
  "success": true
}
```

This endpoint acknowledges health alarms. It allows many alarms to be acknowledged at once by specifying `ids`, or acknowledging all alarms via the `all` flag.

### HTTP Request

`PUT <%= api_url %>/api/health/alarms/acknowledge`

### JSON Parameters

Parameter | Default | Description
--------- | ------- | -----------
ids      | [] | Array of Alarm ID(s)to be updated.
all      | false | Pass `true` to update all alarms instead of passing `ids`. This will update any active alarm that is not already acknowledged.
acknowledged      | true | Pass `false` to unacknowledge the alarm(s) instead of acknowledge them.

## Get All Health Logs

```shell
curl "<%= curl_url %>/api/health/logs" \
  -H "Authorization: BEARER <%= curl_token %>"
```

> The above command returns JSON structured like this:

```json
{
  "logs": [
    {
      "typeCode": "appliance",
      "ts": "2020-01-05T03:09:04Z",
      "level": "ERROR",
      "sourceType": "appliance",
      "message": "[pool-2-thread-7] Failure in api call",
      "hostname": "labs-den-m1",
      "objectId": "1",
      "seq": 106678,
      "_id": "324c518d-eb37-41d8-bf13-1cec8bfa0b05"
    },
    {
      "typeCode": "appliance",
      "ts": "2020-01-05T03:08:59Z",
      "level": "INFO",
      "sourceType": "appliance",
      "message": "[pool-2-thread-7] duplicate key: 9825f604-7dd0-4c5f-b1c2-f3e0769bd95c total: 2 remove count: 2",
      "hostname": "labs-den-m1",
      "objectId": "1",
      "seq": 106522,
      "_id": "e97faab1-32c7-4d08-8025-34f12776c583"
    }
  ],
  "meta": {
    "size": 2,
    "total": 10000,
    "max": "2",
    "offset": 0
  }
}
```

This endpoint retrieves all health logs. These are the logs of the remote appliance itself. These logs show all ui activity and are useful for troubleshooting and auditing.  Stack traces are filtered for <%= application_name %> services. Complete stack traces can be found in /var/log/morpheus/morpheus-ui/current.

### HTTP Request

`GET <%= api_url %>/api/health/logs`

### Query Parameters

Parameter | Default | Description
--------- | ------- | -----------
max | 25 | Max number of results to return
offset | 0 | Offset of records you want to load
sort | ts | Sort order
direction | desc | Sort direction
phrase |  | Filter by wildcard search of fields
startDate | 24 hours ago | Date filter in standard iso8601 format, restricts query to only load logs updated more recently than the date specified. 
endDate |  | Date filter in standard iso8601 format, restricts query to only load logs updated before the date specified.

## Export Health Logs

```shell
curl "<%= curl_url %>/api/health/logs/export" \
  -H "Authorization: BEARER <%= curl_token %>"
```

> The above command returns `Content-Type: "application/octet-stream"` and `Content-disposition: attachment;filename="morpheus-2021-11-17-03-56-03.log"`.

This endpoint downloads the morpheus appliance logs as a file attachment. By default, the most recent 10,000 log entries are returned, with the newest at the end of the file. The format for each log entry is `[$timestamp] $level $message`.

### HTTP Request

`GET <%= api_url %>/api/health/logs/export`

### Query Parameters

Parameter | Default | Description
--------- | ------- | -----------
max | 10000 | Max number of results to return
offset | 0 | Offset of records you want to load
sort | ts | Sort order
direction | desc | Sort direction
reverse | true | Reverse order of records. this true by default when `sort` and `direction` are not passed, but `false` by default if either is passed. This means that by default the newest log entries are the bottom of the file.
phrase |  | Filter by wildcard search of fields
startDate | 24 hours ago | Date filter in standard iso8601 format, restricts query to only load logs updated more recently than the date specified. 
endDate |  | Date filter in standard iso8601 format, restricts query to only load logs updated before the date specified.
